[package]
name = "day-4"
version = "0.1.0"
authors = ["quintas <quintas@textkernel.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
